package com.liyuan.dao;

import com.liyuan.model.MallGoods;
import com.liyuan.model.MallGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MallGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    long countByExample(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int deleteByExample(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int insert(MallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int insertSelective(MallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    MallGoods selectOneByExample(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    MallGoods selectOneByExampleSelective(@Param("example") MallGoodsExample example, @Param("selective") MallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    MallGoods selectOneByExampleWithBLOBs(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    List<MallGoods> selectByExampleSelective(@Param("example") MallGoodsExample example, @Param("selective") MallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    List<MallGoods> selectByExampleWithBLOBs(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    List<MallGoods> selectByExample(MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    MallGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MallGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    MallGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MallGoods record, @Param("example") MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") MallGoods record, @Param("example") MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MallGoods record, @Param("example") MallGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MallGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mall_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MallGoods record);
}